services:
  noetic:
    image: noetic-dev
    build: 
      context: .
      args:
        USERNAME: "dev"
        USER_UID: "1000"
        USER_GID: "1000"
    container_name: noetic-dev
    environment:
      # sharing display and gpu
      - WAYLAND_DISPLAY=${WAYLAND_DISPLAY}
      - XDG_SESSION_TYPE=wayland
      - XDG_RUNTIME_DIR=/run/user/1000
      - DISPLAY=${DISPLAY}
      - QT_X11_NO_MITSHM=1
      - LIBGL_DRI3_DISABLE=1
      - QT_QPA_PLATFORM=xcb 
      - NVIDIA_VISIBLE_DEVICES=all
      - NVIDIA_DRIVER_CAPABILITIES=all
    volumes:
      - /tmp/.X11-unix:/tmp/.X11-unix:rw
      - ${XAUTHORITY:-$HOME/.Xauthority}:/home/dev/.Xauthority:ro
      - ${XDG_RUNTIME_DIR}:/run/user/1000      # monta o dir de runtime do host
      - ../ws:/home/dev/code/polarquest/ws
    devices:
      - /dev/dri:/dev/dri
    gpus: all
    network_mode: "host"
